export const fontFamily = {
    inter: {
        thin: "Inter_100Thin",
        extraLight: "Inter_200ExtraLight",
        light: "Inter_300Light",
        regular: "Inter_400Regular",
        medium: "Inter_500Medium",
        semiBold: "Inter_600SemiBold",
        bold: "Inter_700Bold",
        extraBold: "Inter_800ExtraBold",
        black: "Inter_900Black",
        thinItalic: "Inter_100Thin_Italic",
        extraLightItalic: "Inter_200ExtraLight_Italic",
        lightItalic: "Inter_300Light_Italic",
        regularItalic: "Inter_400Regular_Italic",
        mediumItalic: "Inter_500Medium_Italic",
        semiBoldItalic: "Inter_600SemiBold_Italic",
        boldItalic: "Inter_700Bold_Italic",
        extraBoldItalic: "Inter_800ExtraBold_Italic",
        blackItalic: "Inter_900Black_Italic",
    },
    poppins: {
        thin: "Poppins_100Thin",
        extraLight: "Poppins_200ExtraLight",
        light: "Poppins_300Light",
        regular: "Poppins_400Regular",
        medium: "Poppins_500Medium",
        semiBold: "Poppins_600SemiBold",
        bold: "Poppins_700Bold",
        extraBold: "Poppins_800ExtraBold",
        black: "Poppins_900Black",
        thinItalic: "Poppins_100Thin_Italic",
        extraLightItalic: "Poppins_200ExtraLight_Italic",
        lightItalic: "Poppins_300Light_Italic",
        regularItalic: "Poppins_400Regular_Italic",
        mediumItalic: "Poppins_500Medium_Italic",
        semiBoldItalic: "Poppins_600SemiBold_Italic",
        boldItalic: "Poppins_700Bold_Italic",
        extraBoldItalic: "Poppins_800ExtraBold_Italic",
        blackItalic: "Poppins_900Black_Italic",
    },
    roboto: {
        thin: "Roboto_100Thin",
        thinItalic: "Roboto_100Thin_Italic",
        light: "Roboto_300Light",
        lightItalic: "Roboto_300Light_Italic",
        regular: "Roboto_400Regular",
        regularItalic: "Roboto_400Regular_Italic",
        medium: "Roboto_500Medium",
        mediumItalic: "Roboto_500Medium_Italic",
        bold: "Roboto_700Bold",
        boldItalic: "Roboto_700Bold_Italic",
        black: "Roboto_900Black",
        blackItalic: "Roboto_900Black_Italic",
    },
};